# Generated by Django 5.1.1 on 2025-01-19 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewentry',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.menu'),
        ),
    ]
