# Generated by Django 5.1.1 on 2024-10-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_remove_reviewentry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewentry',
            name='owner_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
