# Generated by Django 5.1.1 on 2024-12-05 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_alter_menu_id'),
        ('review', '0006_reviewentry_owner_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewentry',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.menu'),
        ),
    ]
