# Generated by Django 5.1.1 on 2024-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_reviewentry_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewentry',
            name='menu',
            field=models.CharField(max_length=255),
        ),
    ]
