# Generated by Django 5.1.2 on 2024-10-15 04:50

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
    ]
