# Generated by Django 5.1.2 on 2024-10-26 01:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_alter_menu_specialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
