# Generated by Django 5.1.1 on 2024-10-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_menu_claimed_by'),
        ('explore', '0007_alter_menu_category_alter_menu_city_alter_menu_menu_and_more'),
    ]

    operations = [
    ]
