# Generated by Django 5.1.1 on 2024-10-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_merge_20241026_1415'),
        ('explore', '0008_merge_20241026_1630'),
    ]

    operations = [
    ]
