# Generated by Django 5.1.1 on 2024-10-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinthewheel', '0006_delete_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinhistory',
            name='winnerId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
