# Generated by Django 5.1.1 on 2024-10-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinthewheel', '0008_secrethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinhistory',
            name='note',
            field=models.TextField(default='-'),
        ),
    ]
