# Generated by Django 5.1.2 on 2024-10-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinthewheel', '0009_spinhistory_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrethistory',
            name='note',
            field=models.TextField(default='-'),
        ),
    ]
