# Generated by Django 5.2.dev20240823160747 on 2024-10-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meatup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
