# Generated by Django 5.1.2 on 2024-10-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meatup', '0002_wishlist_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='is_public',
        ),
    ]