# Generated by Django 5.2.dev20240823160747 on 2024-12-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meatup', '0003_meatupmessage'),
        ('meatup', '0003_remove_wishlist_is_public'),
    ]

    operations = [
    ]
