# Generated by Django 5.2.dev20240823160747 on 2024-12-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meatup', '0004_merge_20241204_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeatupMessage',
        ),
    ]
